kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: golang:latest
    commands:
      - go build
  - name: analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonarhost
      sonar_token:
        from_secret: sonartoken