name: Go

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v .
  scan:
    runs-on: ubuntu-latest
    name: Analysis 
    steps:
      - name: SonarQube Scanner
        uses: ItsEcholot/sonarqube-action@v0.0.2
        with:
          host: https://weilbyte.net
          login: ${{ secrets.token }}


      
